"""Supervisor-owned Git gates, reviewed manifests, sequential rendering and QA."""
from __future__ import annotations

import functools
import http.server
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import socketserver
import threading

from .common import PreconditionFailed, Blocked, atomic_json, digest, disk_gate, file_hash, private_dir, run, safe_relative

PROTECTED = ("publication/", "PROFILE.md", "tools/", "instructions/", ".github/", "AGENTS.md", "CLAUDE.md", "shared-files.json", "packages/", "pyproject.toml", "uv.lock", ".git")
SECRET_PATTERNS = (rb"-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----", rb"\b(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_-]{20,}|ya29\.[A-Za-z0-9_-]{12,}|1//[A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)", rb"(?i)(?:client_secret|refresh_token|access_token|api_key)[\"']?\s*[=:]\s*[\"']?[A-Za-z0-9_\-/+]{12,}")


class CandidateViolation(Blocked):
    """Candidate bytes require preserved direct-admin fresh-worktree repair."""


class IgnoredOutputs(CandidateViolation):
    """Known ordinary generated bytes require explicit preserved rebase."""


class OwnerPolicyViolation(Blocked):
    """Inherited Git policy needs owner maintenance, never source rewriting."""

    def __init__(self, message, path=None):
        super().__init__(message)
        self.path = str(safe_relative(path)) if path is not None else None


class Git:
    def __init__(self, repo, lock=None, identity=None):
        self.repo, self.lock = Path(repo).resolve(), lock
        actual = self.metadata_identity(self.repo)
        if identity is not None and actual != identity:
            raise Blocked("Git metadata identity changed after supervisor worktree creation")
        self.identity = identity or actual

    @staticmethod
    def metadata_identity(repo):
        marker = Path(repo) / '.git'
        if marker.is_symlink():
            raise Blocked('Git metadata symlink refused')
        if marker.is_dir():
            gitdir = marker.resolve()
            marker_hash = None
        elif marker.is_file():
            text = marker.read_text()
            if not text.startswith('gitdir: ') or len(text.splitlines()) != 1:
                raise Blocked('invalid Git worktree metadata')
            gitdir = (marker.parent / text.strip()[8:]).resolve()
            marker_hash = file_hash(marker)
        else:
            raise Blocked('Git metadata missing')
        common_file = gitdir / 'commondir'
        common = (gitdir / common_file.read_text().strip()).resolve() if common_file.is_file() else gitdir
        controls = {}
        for path in (common_file, gitdir/'gitdir', common/'config', gitdir/'config.worktree'):
            if path.is_symlink():
                raise Blocked('Git control metadata symlink refused')
            controls[str(path)] = file_hash(path) if path.is_file() else None
        return {'repo': str(Path(repo).resolve()), 'gitdir': str(gitdir), 'common': str(common), 'marker_hash': marker_hash, 'controls': controls}

    def git(self, *args, timeout=120):
        if self.metadata_identity(self.repo) != self.identity:
            raise Blocked('Git metadata changed; no supervisor Git subprocess started')
        argv = ['git', '--git-dir', self.identity['gitdir'], '--work-tree', str(self.repo),
                '-c', 'core.hooksPath=/dev/null', '-c', 'core.fsmonitor=false', '-c', 'core.quotePath=false', '-c', 'protocol.ext.allow=never', *args]
        output=run(argv, self.repo, lock=self.lock, timeout=timeout,filename_output='-z' in args)
        return output if '-z' in args else output.strip()

    def names(self,*args,timeout=120):
        if '-z' not in args:
            raise Blocked('Git filename lists require NUL delimiters')
        return [name for name in self.git(*args,timeout=timeout).split('\0') if name]

    def diff_names(self,*revisions,timeout=120):
        return self.names('diff','--no-renames','--name-only','-z',*revisions,timeout=timeout)

    def committed_changes(self,base,head):
        """Exact ordinary committed-tree SHA256, independent of dirty bytes."""
        import tempfile
        result={}
        entries={}
        for record in self.names('ls-tree','-r','-z',head):
            header,name=record.split('\t',1);entries[name]=header.split()
        for name in self.diff_names(base,head):
            safe_relative(name)
            entry=entries.get(name)
            if not entry or entry[0] not in ('100644','100755') or entry[1]!='blob':
                result[name]=None;continue
            temporary=tempfile.TemporaryDirectory(prefix='school-notes-committed-');path=str(Path(temporary.name)/'blob')
            try:
                if self.metadata_identity(self.repo)!=self.identity:raise Blocked('Git metadata changed before committed blob read')
                run(['git','--git-dir',self.identity['gitdir'],'-c','core.hooksPath=/dev/null','cat-file','blob',entry[2]],self.repo,lock=self.lock,log=path,read_output=False)
                result[name]=file_hash(path)
            finally:
                for item in (path,path+'.stderr'):
                    if os.path.exists(item):os.unlink(item)
                temporary.cleanup()
        return result

    def merge_base(self,base,head):
        # An entirely rewritten history may have no common ancestor. Both
        # exact endpoint objects must still be available for committed diff.
        common=set(self.git('rev-list',base).splitlines()) & set(self.git('rev-list',head).splitlines())
        return self.git('merge-base',base,head) if common else None

    def head(self,timeout=120):
        return self.git("rev-parse", "HEAD",timeout=timeout)

    def source_is_ignored(self,name):
        return bool(self.names('ls-files','--others','--ignored','--exclude-standard','-z','--',':(literal)'+name))

    def source_attributes(self,name):
        fields=self.names('check-attr','-z','filter','working-tree-encoding','text','eol','--',name)
        if len(fields)!=12:raise Blocked('incomplete source Git attribute inventory')
        values={fields[i+1]:fields[i+2] for i in range(0,len(fields),3)}
        for key in ('filter','working-tree-encoding'):
            if values[key] not in ('unspecified','unset'):
                raise OwnerPolicyViolation('source-byte transforming Git attribute: '+name+' '+key+'; owner policy maintenance, observe external range, acknowledge-maintenance, then rebase-candidate; preserve original bytes', name)
        # text=auto/eol=lf may leave binary bytes unchanged. The exact staged
        # blob gate decides actual transformation, without running any filter.
        return values

    def source_policy(self, name, path=None):
        self.source_attributes(name)
        path=Path(path) if path is not None else self.repo/name
        if self.git('hash-object','--path='+name,'--',str(path)) != self.git('hash-object','--no-filters','--',str(path)):
            raise OwnerPolicyViolation('Git normalization would transform exact source bytes: '+name+'; owner policy maintenance, observe external range, acknowledge-maintenance, then rebase-candidate; never rewrite original bytes', name)

    def ordinary_changed_paths(self, root, base):
        """Inventory retained bytes against base using only this pinned Git."""
        root=Path(root).resolve()
        entries={}
        for record in self.names('ls-tree','-r','-z',base):
            header,name=record.split('\t',1);entries[name]=tuple(header.split())
        algorithm=self.git('rev-parse','--show-object-format')
        if algorithm not in ('sha1','sha256'):raise Blocked('unsupported Git object format')
        changed=[]
        for path in sorted(root.rglob('*')):
            name=str(path.relative_to(root))
            if '.git' in path.relative_to(root).parts or path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(root):continue
            try:safe_relative(name)
            except Blocked:
                if name not in entries:continue
                raise Blocked('unsafe inherited filename '+repr(name)+'; owner maintenance required') from None
            h=hashlib.new(algorithm);h.update(f'blob {path.stat().st_size}\0'.encode())
            with path.open('rb') as stream:
                for chunk in iter(lambda:stream.read(1024*1024),b''):h.update(chunk)
            mode='100755' if path.stat().st_mode & 0o111 else '100644'
            if entries.get(name)!=(mode,'blob',h.hexdigest()):changed.append(name)
        return changed

    def visible_outputs(self):
        ignored=self.names('ls-files','--others','--ignored','--exclude-standard','-z','--','wiki','docs')
        if ignored:raise IgnoredOutputs('ignored generated wiki/docs output: '+', '.join(ignored))

    def verify_manifest_tree(self,manifest,ref='HEAD'):
        self.verify_sources([{'path':str(self.repo/item['path']),'sha256':item['sha256']} for item in manifest['pages']+manifest.get('assets',[])],ref)

    def verify_sources(self,sources,ref='HEAD'):
        algorithm=self.git('rev-parse','--show-object-format')
        if algorithm not in ('sha1','sha256'):raise Blocked('unsupported Git object format')
        for source in sources:
            path=Path(source['path']);name=str(path.relative_to(self.repo))
            if file_hash(path)!=source['sha256']:raise Blocked('Git source bytes changed')
            records=self.names('ls-files','--stage','-z','--',':(literal)'+name) if ref==':index' else self.names('ls-tree','-z',ref,'--',':(literal)'+name)
            if len(records)!=1:raise Blocked('source absent from exact commit tree: '+name)
            header,actual_name=records[0].split('\t',1)
            if ref==':index':
                mode,oid,stage=header.split();kind='blob' if stage=='0' else 'unmerged'
            else:mode,kind,oid=header.split()
            if actual_name!=name or kind!='blob' or mode not in ('100644','100755'):
                raise Blocked('source is not an ordinary committed blob: '+name)
            h=hashlib.new(algorithm);h.update(f'blob {path.stat().st_size}\0'.encode())
            with path.open('rb') as stream:
                for chunk in iter(lambda:stream.read(1024*1024),b''):h.update(chunk)
            if oid!=h.hexdigest():raise Blocked('committed source blob differs from reviewed bytes: '+name)

    def clean(self,timeout=120):
        if self.git("status", "--porcelain", "--untracked-files=all",timeout=timeout):
            raise Blocked("dirty interactive checkout: no reset/stash or automatic overwrite")

    def reconciliation_message(self,local,remote,counts=None):
        counts=counts or self.git('rev-list','--left-right','--count',f'{local}...{remote}').split()
        if counts[0]=='0':return 'owner checkout behind origin/main; strict owner-session processing waits for explicit owner fast-forward; standalone observation can fast-forward a clean behind checkout'
        if counts[1]=='0':return 'local ahead of origin/main: unpushed owner commits or possible remote history rewrite/rewind; owner must assess local and remote history before choosing reconciliation; no automatic push/reset'
        return 'local and origin/main diverged: concurrent owner changes or possible remote history rewrite; owner must assess both histories and explicitly align checkout before observation/maintenance; no automatic push/reset'

    def inspect(self, fetch=True, *, allow_fast_forward=False):
        # Inspection never moves owner HEAD unless normal standalone observation
        # explicitly opts in. Administrative/build/commit gates keep this default.
        self.clean()
        if fetch:
            self.git("fetch", "--no-tags", "origin", "main")
        local, remote = self.head(), self.git("rev-parse", "refs/remotes/origin/main")
        if local != remote:
            counts = self.git("rev-list", "--left-right", "--count", f"{local}...{remote}").split()
            if counts[0] != "0" or not allow_fast_forward:
                raise Blocked(self.reconciliation_message(local,remote,counts))
            self.git("merge", "--ff-only", remote)
        return self.head()

    def estimate(self):
        # Include all tracked and untracked ordinary files, including ignored
        # source evidence retained in this checkout. Never assume a 256MB tree.
        return sum(p.stat().st_size for p in self.repo.rglob("*") if p.is_file() and not p.is_symlink() and ".git" not in p.parts)

    def worktree(self, destination, base, identity=None):
        if Path(destination).exists():
            candidate = Git(destination, self.lock, identity)
            if candidate.git("rev-parse", "--show-toplevel") != str(Path(destination).resolve()):
                raise Blocked("retained candidate is not the expected worktree")
            return candidate
        self.git("worktree", "add", "--detach", str(destination), base)
        return Git(destination, self.lock)

    def changes(self, base, supervisor_paths=(), sources=()):
        bindings={str(Path(source['path']).relative_to(self.repo)):source['sha256'] for source in sources}
        for name, sha in bindings.items():
            path=self.repo/safe_relative(name)
            if not name.startswith('sources/') or path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(self.repo) or file_hash(path)!=sha:
                raise CandidateViolation('agent changed/missing supervisor-bound immutable source: '+name)
        self.visible_outputs()
        # Worktree git diff may execute clean filters merely to find names.
        # Compare raw local blobs to the immutable base tree before consulting
        # attributes or asking Git to normalize anything. Committed tree and
        # index filename inventories do not run worktree filters.
        entries = {}
        for record in self.names('ls-tree', '-r', '-z', base):
            header, name = record.split('\t', 1)
            mode, kind, oid = header.split()
            entries[name] = (mode, kind, oid)
        names = set(entries) | set(self.names('ls-files', '-z')) | set(self.names('ls-files', '--others', '--exclude-standard', '-z'))
        algorithm = self.git('rev-parse', '--show-object-format')
        if algorithm not in ('sha1', 'sha256'):raise Blocked('unsupported Git object format')
        result = {}
        for name in sorted(set(names)):
            try:safe_relative(name)
            except Blocked:
                if name not in entries:raise CandidateViolation('unsafe candidate filename: '+repr(name)) from None
                raise Blocked('unsafe inherited filename '+repr(name)+'; owner maintenance required') from None
            path = self.repo / name
            entry = entries.get(name)
            if path.is_symlink():
                data = os.fsencode(os.readlink(path))
                h = hashlib.new(algorithm);h.update(f'blob {len(data)}\0'.encode());h.update(data)
                if entry == ('120000', 'blob', h.hexdigest()):continue
            elif path.is_file() and path.resolve().is_relative_to(self.repo):
                h = hashlib.new(algorithm);h.update(f'blob {path.stat().st_size}\0'.encode())
                with path.open('rb') as stream:
                    for chunk in iter(lambda: stream.read(1024 * 1024), b''):h.update(chunk)
                mode = '100755' if path.stat().st_mode & 0o111 else '100644'
                if entry == (mode, 'blob', h.hexdigest()):continue
            if name not in supervisor_paths and (Path(name).name in ('.gitattributes', '.gitignore') or any(name == p.rstrip("/") or name.startswith(p if p.endswith("/") else p + "/") for p in PROTECTED)):
                raise CandidateViolation(f"agent modified protected path: {name}")
            if name not in supervisor_paths and not name.startswith(("wiki/", "sources/", "docs/review/", "docs/evidence/")):
                raise CandidateViolation(f"unapproved candidate path: {name}")
            if path.is_symlink() or not path.is_file() or not path.resolve().is_relative_to(self.repo.resolve()):
                raise CandidateViolation(f"candidate deletion/symlink requires manual review: {name}")
            if name.startswith('sources/') and name not in bindings:
                raise CandidateViolation('unbound sources write: acquisition is supervisor-only; preserve snapshot and rebase candidate: '+name)
            self.source_attributes(name)
            if self.git('hash-object', '--path='+name, '--', name) != self.git('hash-object', '--no-filters', '--', name):
                if name in bindings:
                    raise OwnerPolicyViolation('Git normalization would transform exact source bytes: '+name+'; owner policy maintenance, observe external range, acknowledge-maintenance, then rebase-candidate; never rewrite original bytes', name)
                raise CandidateViolation('candidate Git normalization changes reviewed bytes; write LF and rebase preserved candidate: '+name)
            result[name] = file_hash(path)
        return result

    def push_reconcile(self, effect):
        try:
            self.git("fetch", "--no-tags", "origin", "main")
            remote = self.git("rev-parse", "refs/remotes/origin/main")
            commit = effect["artifact_hash"]
            if self.git("rev-list", remote).splitlines().count(commit):
                return {"verified": True, "external_id": commit, "commit": commit, "target": effect["target"]}
            # Remote history obtained successfully and exact commit absent.
            return {"absent":True,"remote_head":remote,"artifact_hash":commit,"target":effect["target"]}
        except Blocked:
            return None

    def commit(self, job, expected_changes, review_files, identity, manifest_path=None, manifest=None):
        review_names = {f"docs/review/school-notes-{job['id']}-{digest(str(path))[:12]}-{Path(path).name}" for path in review_files}
        config_paths=job['payload'].get('supervisor_config_paths',{})
        supervisor_names = review_names | ({manifest_path} if manifest_path else set()) | set(config_paths)
        if any(file_hash(self.repo/name)!=sha for name,sha in config_paths.items()):
            raise Blocked('approved configuration bytes changed')
        actual = self.changes(job["payload"]["base"], supervisor_names,job['payload'].get('git_sources',[]))
        if {name: sha for name, sha in actual.items() if name in config_paths or name not in supervisor_names} != expected_changes:
            raise Blocked("candidate changed after review")
        if manifest_path in actual and json.loads((self.repo / manifest_path).read_text()) != manifest:
            raise Blocked("retained supervisor manifest differs from reviewed configuration")
        if not identity.get("name") or not identity.get("email") or identity["email"].endswith(".invalid"):
            raise Blocked("real approved Git author identity is required")
        for path in review_files:
            # Supervisor-owned review evidence, after candidate hash gate.
            dest = self.repo / "docs/review" / f"school-notes-{job['id']}-{digest(str(path))[:12]}-{Path(path).name}"
            dest.parent.mkdir(parents=True, exist_ok=True)
            if dest.exists() and file_hash(dest) != file_hash(path):
                raise Blocked("existing review record differs")
            if not dest.exists():
                shutil.copyfile(path, dest)
        self.visible_outputs()
        reviewed = {**expected_changes, **{name:file_hash(self.repo/name) for name in review_names}}
        for name in set(reviewed) | ({manifest_path} if manifest_path else set()):self.source_attributes(name)
        # Stage exact reviewed files, avoiding unchanged directories whose
        # attributes have not been checked or whose index state was preserved.
        for name in sorted(reviewed):
            self.git('add','--',name)
        if manifest_path:
            path = self.repo / safe_relative(manifest_path)
            if not str(manifest_path).startswith("publication/") or manifest.get("mode") != "private-preview":
                raise Blocked("supervisor may update only the private reviewed manifest here")
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
            self.git("add", "--", manifest_path)
        try:
            staged=set(self.diff_names('--cached',job['payload']['base']))
            if not staged <= set(reviewed) | ({manifest_path} if manifest_path else set()):
                raise Blocked('unreviewed staged path; existing index preserved')
            self.verify_sources(job['payload'].get('git_sources',[]),':index')
            self.verify_sources([{'path':str(self.repo/name),'sha256':sha} for name,sha in reviewed.items()],':index')
            if manifest:self.verify_manifest_tree(manifest,':index')
        except Blocked as error:
            raise PreconditionFailed('no commit created; staged source/manifest blob gate: '+str(error)) from None
        message = f"School Notes: {job['kind']} revision {job['revision_seq']}\n\nCo-Authored-By: School Notes (gpt-6.1-sol/high) <agent@school-notes.invalid>"
        self.git("-c", f"user.name={identity['name']}", "-c", f"user.email={identity['email']}", "commit", "-m", message)
        self.verify_sources(job['payload'].get('git_sources',[]))
        self.verify_sources([{'path':str(self.repo/name),'sha256':sha} for name,sha in reviewed.items()])
        if manifest:self.verify_manifest_tree(manifest)
        return self.head()

    def reconcile_commit(self, effect, job, expected_changes, review_files, manifest_path, manifest):
        head = self.head()
        base = job["payload"]["base"]
        if head == base:
            # A failed git commit may leave supervisor files/index entries.
            # Repeating commit() requires its exact pre-review content gate.
            return {"absent": True}
        self.clean()
        if self.git("rev-parse", "HEAD^") != base:
            raise Blocked("retained commit has unexpected ancestry")
        expected = dict(expected_changes)
        for path in review_files:
            name = f"docs/review/school-notes-{job['id']}-{digest(str(path))[:12]}-{Path(path).name}"
            expected[name] = file_hash(path)
        names = set(self.diff_names(base,head))
        # An unchanged manifest/review path need not be in the final diff, but
        # every changed path must belong to the exact reviewed set.
        allowed = set(expected) | {manifest_path}
        if not names <= allowed or any(file_hash(self.repo / name) != sha for name, sha in expected.items()):
            raise Blocked("retained commit differs from reviewed content/evidence")
        if json.loads((self.repo / manifest_path).read_text()) != manifest:
            raise Blocked("retained commit private manifest differs from accepted review")
        self.verify_sources(job['payload'].get('git_sources',[]))
        self.verify_sources([{'path':str(self.repo/name),'sha256':sha} for name,sha in expected.items()])
        if manifest:self.verify_manifest_tree(manifest)
        return {"verified": True, "external_id": head, "commit": head}


def scan(paths, max_new_bytes, max_total_bytes, repo):
    total = 0
    for path in paths:
        path = Path(path)
        if not path.is_file() or path.is_symlink():
            raise Blocked("scan input missing or symlinked")
        total += path.stat().st_size
        data = path.read_bytes()
        if any(re.search(p, data) for p in SECRET_PATTERNS):
            raise Blocked(f"secret scan blocked file: {path.name}; matched text omitted")
    if total > max_new_bytes:
        raise Blocked(f"new content/binary limit: {total} > {max_new_bytes}")
    size = sum(p.stat().st_size for p in Path(repo).rglob("*") if p.is_file() and ".git" not in p.parts)
    if size > max_total_bytes:
        raise Blocked(f"repository growth limit: {size} > {max_total_bytes}")


def validate_manifest(manifest):
    allowed = {"version", "title", "mode", "base", "pages", "assets", "collections", "privateLinks", "citationOnlyLinks", "license", "branding",
               "site", "reviewRecord", "publicationApproved", "feedbackRepository"}
    if not isinstance(manifest, dict) or set(manifest) - allowed or manifest.get("mode") not in ("private-preview", "public") or not isinstance(manifest.get("pages"), list) or not manifest["pages"]:
        raise Blocked("invalid site manifest proposal")
    if not isinstance(manifest.get("title"), str) or not manifest["title"].strip() or not isinstance(manifest.get("base"), str) or not manifest["base"].startswith("/") or not manifest["base"].endswith("/"):
        raise Blocked("manifest title/base invalid")
    item_fields = {"pages": {"path", "sha256", "group", "navigation", "navigationLabel", "publicationReviewed", "publicEdits", "omitSections"},
                   "assets": {"path", "sha256", "publicationReviewed", "rights", "rightsEvidence"}}
    for key, fields in item_fields.items():
        if not isinstance(manifest.get(key, []), list):
            raise Blocked("manifest item list invalid")
        for item in manifest.get(key, []):
            if not isinstance(item, dict) or set(item) - fields or not isinstance(item.get("path"), str):
                raise Blocked("manifest item schema invalid")
            safe_relative(item["path"])
            for text in ("group", "navigation", "navigationLabel", "rights", "rightsEvidence", "sha256"):
                if text in item and not isinstance(item[text], str):
                    raise Blocked("manifest item text field invalid")
            if "publicationReviewed" in item and type(item["publicationReviewed"]) is not bool:
                raise Blocked("manifest review flag invalid")
            if "omitSections" in item and (not isinstance(item["omitSections"], list) or not all(isinstance(t, str) for t in item["omitSections"])):
                raise Blocked("manifest omitted sections invalid")
            if "publicEdits" in item:
                if not isinstance(item["publicEdits"], list) or any(not isinstance(e, dict) or set(e) != {"before", "after", "reason"} or not all(isinstance(v, str) for v in e.values()) for e in item["publicEdits"]):
                    raise Blocked("manifest public edits invalid")
    if not isinstance(manifest.get("collections", []), list):
        raise Blocked("manifest collection list invalid")
    for collection in manifest.get("collections", []):
        if not isinstance(collection, dict) or set(collection) - {"id", "title", "pages", "pdf", "group"} or not all(isinstance(collection.get(k), str) for k in ("id", "title")) or not isinstance(collection.get("pages"), list) or not all(isinstance(p, str) for p in collection["pages"]):
            raise Blocked("manifest collection schema invalid")
        if "pdf" in collection and type(collection["pdf"]) is not bool:
            raise Blocked("manifest PDF flag invalid")
    for key in ("privateLinks", "branding", "license"):
        if key in manifest and not isinstance(manifest[key], dict):
            raise Blocked("manifest mapping invalid")
    if "privateLinks" in manifest and not all(isinstance(k, str) and isinstance(v, str) and v.startswith("https://github.com/") for k, v in manifest["privateLinks"].items()):
        raise Blocked("manifest private link schema invalid")
    if "license" in manifest and (set(manifest["license"]) != {"id", "attribution"} or not all(isinstance(v, str) for v in manifest["license"].values())):
        raise Blocked("manifest license schema invalid")
    if "branding" in manifest and (set(manifest["branding"]) != {"light", "dark"} or any(not isinstance(v, dict) or set(v) != {"path", "sha256"} or not all(isinstance(s, str) for s in v.values()) for v in manifest["branding"].values())):
        raise Blocked("manifest branding schema invalid")
    if "citationOnlyLinks" in manifest and (not isinstance(manifest["citationOnlyLinks"], list) or not all(isinstance(v, str) for v in manifest["citationOnlyLinks"])):
        raise Blocked("manifest citation list invalid")
    for key in ("site", "reviewRecord", "feedbackRepository"):
        if key in manifest and not isinstance(manifest[key], str):
            raise Blocked("manifest text schema invalid")
    if "publicationApproved" in manifest and type(manifest["publicationApproved"]) is not bool:
        raise Blocked("manifest publication flag invalid")
    return manifest


def manifest_with_hashes(repo, manifest):
    validate_manifest(manifest)
    result = json.loads(json.dumps(manifest))
    for key in ("pages", "assets"):
        seen = set()
        for item in result.get(key, []):
            if not isinstance(item, dict) or "path" not in item:
                raise Blocked("invalid manifest item")
            path = safe_relative(item["path"])
            if str(path) in seen or not str(path).startswith("wiki/"):
                raise Blocked("manifest duplicate/non-wiki path")
            seen.add(str(path))
            target = Path(repo) / path
            if target.is_symlink() or not target.resolve().is_relative_to(Path(repo).resolve()):
                raise Blocked("manifest path escapes candidate")
            item["sha256"] = file_hash(target)
    for item in result.get("branding", {}).values():
        path = safe_relative(item["path"])
        target = Path(repo) / path
        if not re.fullmatch(r"publication/assets/[^/]+\.png", str(path)) or target.is_symlink() or not target.resolve().is_relative_to(Path(repo).resolve()):
            raise Blocked("branding must be a contained publication/assets PNG")
        if target.read_bytes()[:8] != b"\x89PNG\r\n\x1a\n":
            raise Blocked("branding PNG signature mismatch")
        item["sha256"] = file_hash(target)
    return result


def merge_manifest(existing, proposed):
    """Agent proposals can add/reorder pages and collection membership only.

    Base, rights, branding and all other configuration remain a direct human
    maintenance operation. Existing entries may never silently disappear.
    """
    validate_manifest(existing)
    validate_manifest(proposed)
    old = json.loads(json.dumps(existing))
    for key in set(old) | set(proposed):
        if key not in ("pages", "collections") and old.get(key) != proposed.get(key):
            raise Blocked(f"manifest configuration requires human admin: {key}")
    prior = {p["path"]: p for p in old["pages"]}
    current = {p["path"]: p for p in proposed["pages"]}
    if len(current) != len(proposed["pages"]) or not prior.keys() <= current.keys():
        raise Blocked("manifest cannot remove or duplicate existing pages")
    for name, item in prior.items():
        if {k:v for k,v in item.items() if k != "sha256"} != {k:v for k,v in current[name].items() if k != "sha256"}:
            raise Blocked("existing page options require human admin")
    before = {c["id"]: c for c in old.get("collections", [])}
    after = {c["id"]: c for c in proposed.get("collections", [])}
    if before.keys() != after.keys() or len(after) != len(proposed.get("collections", [])):
        raise Blocked("collection configuration requires human admin")
    for name, item in before.items():
        if ({k:v for k,v in item.items() if k != "pages"} != {k:v for k,v in after[name].items() if k != "pages"}
                or not set(item["pages"]) <= set(after[name]["pages"]) or not set(after[name]["pages"]) <= current.keys()):
            raise Blocked("collection cannot drop existing membership or change configuration")
    return json.loads(json.dumps(proposed))


def agent_manifest(repo, existing, proposed):
    """Invalid model proposals need preserved candidate repair, before review."""
    try:
        if isinstance(proposed,str):proposed=json.loads(proposed)
        proposal=merge_manifest(existing, proposed if proposed is not None else existing)
        manifest_with_hashes(repo,proposal)
        if proposal.get('mode')!='private-preview':raise Blocked('ingest may propose only private preview configuration')
        return proposal
    except (Blocked,OSError,ValueError,RecursionError) as error:
        raise CandidateViolation('invalid agent manifest proposal: '+str(error)) from None


def review_gate(result, envelope, *, require_visual=True, require_public=False):
    if result["status"] != "complete" or result["uncertainties"]:
        raise Blocked("review has unresolved findings/uncertainties")
    required = {f["path"] for f in envelope["inputs"]}
    if set(result["coverage"]) != required or not result["evidence"]:
        raise Blocked("review does not cover every bound source/text/figure/PDF page")
    review = result.get("review")
    checks = ["content", "source_coverage", "privacy", "provenance", "curriculum", "reading_order", "formulae", "banners"]
    if require_visual:
        checks += ["visual", "all_pdf_pages"]
    if require_public:
        checks += ["public_privacy", "asset_rights"]
    if not isinstance(review, dict) or any(review.get(k) is not True for k in checks):
        raise Blocked("review scope lacks required explicit checks")


class Renderer:
    def __init__(self, config, lock, window):
        self.config, self.lock, self.window = config, lock, window

    def build(self, repo, manifest, directory):
        timeout = int(self.config.get("timeout", 300))
        self.window.require(timeout + 10)
        directory = private_dir(directory)
        disk_gate(directory, self.config.get("estimate_bytes", 512 * 1024**2), self.config.get("reserve_bytes", 4 * 1024**3))
        config_path = directory / "manifest.json"
        atomic_json(config_path, manifest)
        build = directory / "build"
        # A complete retained build is reusable only for exactly the same inputs.
        receipt = directory / "complete.json"
        if receipt.exists():
            record = json.loads(receipt.read_text())
            if record["manifest_hash"] != digest(manifest) or record["artifacts"] != self.artifacts(build):
                raise Blocked("retained render inputs/artifacts changed")
            return build, record["images"]
        if build.exists():
            raise Blocked("partial render retained: use a fresh render attempt directory")
        root = Path(self.config["package"])
        run([self.config["node"], str(root / "cli.mjs"), "build", "--repo", str(repo), "--config", str(config_path), "--output", str(build), "--browser", self.config["browser"], "--pdf-cache", self.config["pdf_cache"]], repo, timeout=timeout, lock=self.lock, log=directory / "render.log")
        images = self.pdf_images(build, directory / "pdf-pages")
        self.browser(build, root, directory)
        if manifest["mode"] == "public":
            run([self.config["python"], str(root / "check-public.py"), str(build)], repo, timeout=timeout, lock=self.lock, log=directory / "privacy.log")
        atomic_json(receipt, {"manifest_hash": digest(manifest), "artifacts": self.artifacts(build), "images": images})
        return build, images

    def pdf_images(self, build, destination):
        destination = private_dir(destination)
        images = []
        documents = []
        for number, pdf in enumerate(sorted((Path(build) / "site/pdf").glob("*.pdf")), 1):
            info = run([self.config["pdfinfo"], str(pdf)], destination, lock=self.lock)
            match = re.search(r"Pages:\s+(\d+)", info)
            if not match:
                raise Blocked("PDF page count missing")
            count = int(match[1])
            prefix = destination / f"{number:03d}"
            # Sequential renderer: never launch four PDF render children.
            disk_gate(destination, count * 3 * 1024**2, self.config.get("reserve_bytes", 4 * 1024**3))
            run([self.config["pdftoppm"], "-scale-to", "1600", "-png", str(pdf), str(prefix)], destination, timeout=300, lock=self.lock)
            pages = sorted(destination.glob(f"{number:03d}-*.png"), key=lambda p: int(p.stem.rsplit("-", 1)[1]))
            if len(pages) != count:
                raise Blocked("PDF image coverage incomplete")
            images.extend({"path": str(p), "sha256": file_hash(p), "kind": "pdf-page", "page_key": f"{pdf.name}:{i}", "document_sha256": file_hash(pdf)} for i, p in enumerate(pages, 1))
            documents.append({"path": str(pdf), "sha256": file_hash(pdf), "pages": count})
        atomic_json(destination / "manifest.json", {"documents": documents, "images": images})
        if not documents:
            raise Blocked("pilot requires at least one PDF collection")
        return images

    def browser(self, build, package, directory):
        class Quiet(http.server.SimpleHTTPRequestHandler):
            def log_message(self, *_):
                pass
        payload = json.loads((build / "payload.json").read_text())
        # Route the configured base to the site root using a supervisor-only
        # handler. No browser receives private job-directory files.
        site = build / "site"
        base = payload["base"]
        class Handler(Quiet):
            def translate_path(self, path):
                if path.startswith(base):
                    path = "/" + path[len(base):]
                return super().translate_path(path)
        handler = functools.partial(Handler, directory=str(site))
        with socketserver.TCPServer(("127.0.0.1", 0), handler) as server:
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                address = f"http://127.0.0.1:{server.server_address[1]}"
                run([self.config["node"], str(package / "check-browser.mjs"), address, str(build / "payload.json"), self.config["browser"], str(build / "browser-report.json")], package, timeout=self.config.get("timeout", 300), lock=self.lock, log=directory / "browser.log")
                result = json.loads((build / "browser-report.json").read_text())
                if result.get("errors") != [] or len(result.get("pages", [])) != len(payload["pages"]) * 6 or not result.get("search", {}).get("count"):
                    raise Blocked("browser/search coverage incomplete")
            finally:
                server.shutdown()
                thread.join(timeout=2)

    @staticmethod
    def artifacts(build):
        return {p.relative_to(build).as_posix(): file_hash(p) for p in sorted(Path(build).rglob("*")) if p.is_file() and not p.is_symlink()}
